apiVersion: v1
entries:
  webapp:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-07-06T09:43:36.959789657-04:00"
    description: A Helm chart for Kubernetes
    digest: 03e37202d06d7530daa7d6bd065409ce87acf1a751c82e0b3fc4c25f1c18f726
    name: webapp
    type: application
    urls:
    - https://marvin-garcia.github.io/aks-playground/WebApp/Helm/webapp-0.1.0.tgz
    version: 0.1.0
generated: "2022-07-06T09:43:36.958952959-04:00"
