# apiVersion: source.toolkit.fluxcd.io/v1beta1
# kind: HelmRepository
# metadata:
#   name: ingress-nginx
# spec:
#   interval: 30m
#   url: https://kubernetes.github.io/ingress-nginx
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: ingress-nginx
spec:
  interval: 30m
  url: https://github.com/marvin-garcia/aks-playground
  ref:
    branch: main