name: voteapp
replicaCount: 3

serviceAccount:
  create: true
  annotations: {}
  name: voteapp-sa

image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: ""

ports:
- containerPort: 80
  name: http
  protocol: TCP

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}