# Default values
# https://github.com/bitnami/charts/blob/master/bitnami/redis/values.yaml
replica:
  replicaCount: 1
auth:
  enabled: false
usePassword: false
cluster:
  enabled: false
master:
  persistence:
    enabled: false