apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: cluster-config
spec:
  values:
    controller:
      ingressClassByName: true
      ingressClassResource:
        enabled: true
        name: nginx
        controllerValue: k8s.io/nginx
      replicaCount: 2
      service:
        type: LoadBalancer
        externalIPs:
        - '172.16.1.4'
