---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: webapp
  namespace: cluster-config
spec:
  targetNamespace: webapp
  releaseName: webapp
  chart:
    spec:
      chart: webapp
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: webapp
        namespace: cluster-config
  interval: 1m
  install:
    remediation:
      retries: 3
  values:
    image:
      # tag: "2207061318"
      tag: "2207061349"
    ingress:
      enabled: true
      className: nginx
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
      hosts:
        - paths:
            - path: /
              pathType: Prefix
    service:
      type: ClusterIP
    replicaCount: 2