---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: userapi
  namespace: cluster-config
spec:
  targetNamespace: userapi
  releaseName: userapi
  chart:
    spec:
      chart: userapi
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: userapi
        namespace: cluster-config
  interval: 1m
  install:
    remediation:
      retries: 3
  values:
    ingress:
      enabled: true
      className: nginx
    service:
      type: ClusterIP
    replicaCount: 3