apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: cluster-config
spec:
  targetNamespace: nginx
  releaseName: nginx-ingress
  chart:
    spec:
      chart: ./infrastructure/ingress-nginx/chart
      # sourceRef:
      #   kind: HelmRepository
      #   name: ingress-nginx
      #   namespace: cluster-config
      # version: "4.1.4"
  interval: 1h
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml
  values:
    controller:
      ingressClassByName: true
      ingressClassResource:
        controllerValue: k8s.io/nginx
        enabled: true
        name: nginx
      replicaCount: 2
      service:
        type: NodePort
      repository: k8s.gcr.io/ingress-nginx/controller
        tag: "v1.1.1"
