apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: cluster-config
spec:
  targetNamespace: nginx
  releaseName: ingress-nginx-controller
  chart:
    spec:
      chart: nginx-ingress-controller
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: cluster-config
      version: "4.1.4"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml
  values:
    controller:
      ingressClassByName: true
      ingressClassResource:
        controllerValue: k8s.io/ingress-test
        enabled: true
        name: nginx
      replicaCount: 2
      service:
        type: NodePort
